micronaut:
  application:
    name: mnSecurityJwt
  server:
    context-path: /jwtauthservice
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
